//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeadsetInDev {
            get {
                return ((string)(this["HeadsetInDev"]));
            }
            set {
                this["HeadsetInDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeadsetOutDev {
            get {
                return ((string)(this["HeadsetOutDev"]));
            }
            set {
                this["HeadsetOutDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsAccounts Accounts {
            get {
                return ((global::FSClient.SettingsAccounts)(this["Accounts"]));
            }
            set {
                this["Accounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpeakerInDev {
            get {
                return ((string)(this["SpeakerInDev"]));
            }
            set {
                this["SpeakerInDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpeakerOutDev {
            get {
                return ((string)(this["SpeakerOutDev"]));
            }
            set {
                this["SpeakerOutDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RingDev {
            get {
                return ((string)(this["RingDev"]));
            }
            set {
                this["RingDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsSofia Sofia {
            get {
                return ((global::FSClient.SettingsSofia)(this["Sofia"]));
            }
            set {
                this["Sofia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FrontOnIncoming {
            get {
                return ((bool)(this["FrontOnIncoming"]));
            }
            set {
                this["FrontOnIncoming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncomingBalloons {
            get {
                return ((bool)(this["IncomingBalloons"]));
            }
            set {
                this["IncomingBalloons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeadsetDevice {
            get {
                return ((string)(this["HeadsetDevice"]));
            }
            set {
                this["HeadsetDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearDTMFS {
            get {
                return ((bool)(this["ClearDTMFS"]));
            }
            set {
                this["ClearDTMFS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseNumberOnlyInput {
            get {
                return ((bool)(this["UseNumberOnlyInput"]));
            }
            set {
                this["UseNumberOnlyInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsUpgrade {
            get {
                return ((bool)(this["SettingsUpgrade"]));
            }
            set {
                this["SettingsUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsEventSocket EventSocket {
            get {
                return ((global::FSClient.SettingsEventSocket)(this["EventSocket"]));
            }
            set {
                this["EventSocket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsPluginDataCollection HeadsetPlugins {
            get {
                return ((global::FSClient.SettingsPluginDataCollection)(this["HeadsetPlugins"]));
            }
            set {
                this["HeadsetPlugins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsPluginDataCollection ContactPlugins {
            get {
                return ((global::FSClient.SettingsPluginDataCollection)(this["ContactPlugins"]));
            }
            set {
                this["ContactPlugins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recordings")]
        public string RecordingPath {
            get {
                return ((string)(this["RecordingPath"]));
            }
            set {
                this["RecordingPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OnStart")]
        public string CheckForUpdates {
            get {
                return ((string)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://fsclient.fluky.biz/version")]
        public string UpdateURL {
            get {
                return ((string)(this["UpdateURL"]));
            }
            set {
                this["UpdateURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UPNPNAT {
            get {
                return ((bool)(this["UPNPNAT"]));
            }
            set {
                this["UPNPNAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DirectSipDial {
            get {
                return ((bool)(this["DirectSipDial"]));
            }
            set {
                this["DirectSipDial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public string GuiStartup {
            get {
                return ((string)(this["GuiStartup"]));
            }
            set {
                this["GuiStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Steel")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeyboardFocusIncomingCall {
            get {
                return ((bool)(this["KeyboardFocusIncomingCall"]));
            }
            set {
                this["KeyboardFocusIncomingCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsConference Conference {
            get {
                return ((global::FSClient.SettingsConference)(this["Conference"]));
            }
            set {
                this["Conference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTopDuringCall {
            get {
                return ((bool)(this["AlwaysOnTopDuringCall"]));
            }
            set {
                this["AlwaysOnTopDuringCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GlobalHotKey {
            get {
                return ((string)(this["GlobalHotKey"]));
            }
            set {
                this["GlobalHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GlobalAnsHotKey {
            get {
                return ((string)(this["GlobalAnsHotKey"]));
            }
            set {
                this["GlobalAnsHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GlobalEndHotKey {
            get {
                return ((string)(this["GlobalEndHotKey"]));
            }
            set {
                this["GlobalEndHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GlobalMuteHotKey {
            get {
                return ((string)(this["GlobalMuteHotKey"]));
            }
            set {
                this["GlobalMuteHotKey"] = value;
            }
        }
    }
}
