//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeadsetInDev {
            get {
                return ((string)(this["HeadsetInDev"]));
            }
            set {
                this["HeadsetInDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeadsetOutDev {
            get {
                return ((string)(this["HeadsetOutDev"]));
            }
            set {
                this["HeadsetOutDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsAccounts Accounts {
            get {
                return ((global::FSClient.SettingsAccounts)(this["Accounts"]));
            }
            set {
                this["Accounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpeakerInDev {
            get {
                return ((string)(this["SpeakerInDev"]));
            }
            set {
                this["SpeakerInDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpeakerOutDev {
            get {
                return ((string)(this["SpeakerOutDev"]));
            }
            set {
                this["SpeakerOutDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RingDev {
            get {
                return ((string)(this["RingDev"]));
            }
            set {
                this["RingDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsSofia Sofia {
            get {
                return ((global::FSClient.SettingsSofia)(this["Sofia"]));
            }
            set {
                this["Sofia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FrontOnIncoming {
            get {
                return ((bool)(this["FrontOnIncoming"]));
            }
            set {
                this["FrontOnIncoming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncomingBalloons {
            get {
                return ((bool)(this["IncomingBalloons"]));
            }
            set {
                this["IncomingBalloons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeadsetDevice {
            get {
                return ((string)(this["HeadsetDevice"]));
            }
            set {
                this["HeadsetDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearDTMFS {
            get {
                return ((bool)(this["ClearDTMFS"]));
            }
            set {
                this["ClearDTMFS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseNumberOnlyInput {
            get {
                return ((bool)(this["UseNumberOnlyInput"]));
            }
            set {
                this["UseNumberOnlyInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsUpgrade {
            get {
                return ((bool)(this["SettingsUpgrade"]));
            }
            set {
                this["SettingsUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsEventSocket EventSocket {
            get {
                return ((global::FSClient.SettingsEventSocket)(this["EventSocket"]));
            }
            set {
                this["EventSocket"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsPluginDataCollection HeadsetPlugins {
            get {
                return ((global::FSClient.SettingsPluginDataCollection)(this["HeadsetPlugins"]));
            }
            set {
                this["HeadsetPlugins"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::FSClient.SettingsPluginDataCollection ContactPlugins {
            get {
                return ((global::FSClient.SettingsPluginDataCollection)(this["ContactPlugins"]));
            }
            set {
                this["ContactPlugins"] = value;
            }
        }
    }
}